### ISSUE TITLE
MySQL integration

### ISSUE THREAD

**Issue by salahcgp** [laqul/laqul#7]
I downloaded laqul on Mac, mySQL. I am able to install the whole package without any error. Even tables are being created with seed data into the mysql db. But when I run the server I get laravel's default welcome blade template instead of laqul. Hope you will have a look. thank you.

**Comment by laqul** [comment]
Hello @salahcgp this is because in this project laravel acts as an API only, you must not access laravel directly, you must do it through the client. install the client and execute the command "quasar dev", by default it should be showed in localhost:8080, laravel in localhost:8000 and client-backend en localhost:8001, check the readme file and try again
